[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build]
cmds = ["NODE_OPTIONS='--max-old-space-size=450' NEXT_TELEMETRY_DISABLED=1 next build"]

[start]
cmd = "node_modules/.bin/next start"
